# Generated by Django 3.0.5 on 2020-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0002_auto_20200429_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eco_upload_module_1',
            name='File',
            field=models.FileField(upload_to='eco/module1'),
        ),
        migrations.AlterField(
            model_name='eco_upload_module_2',
            name='File',
            field=models.FileField(upload_to='eco/module2'),
        ),
        migrations.AlterField(
            model_name='eco_upload_module_3',
            name='File',
            field=models.FileField(upload_to='eco/module3'),
        ),
        migrations.AlterField(
            model_name='eco_upload_module_4',
            name='File',
            field=models.FileField(upload_to='eco/module4'),
        ),
        migrations.AlterField(
            model_name='eco_upload_module_5',
            name='File',
            field=models.FileField(upload_to='eco/module5'),
        ),
        migrations.AlterField(
            model_name='eco_upload_module_6',
            name='File',
            field=models.FileField(upload_to='eco/module6'),
        ),
    ]
