# Generated by Django 3.0.5 on 2020-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma', '0002_maths_upload_module_1_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maths_upload_module_1',
            name='File',
            field=models.FileField(upload_to='maths/module1'),
        ),
    ]
