# Generated by Django 3.0.5 on 2020-04-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma', '0004_auto_20200427_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='maths_upload_module_2',
            name='Title',
            field=models.CharField(default='enter subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_2',
            name='File',
            field=models.FileField(upload_to='maths/module2'),
        ),
    ]
