# Generated by Django 3.0.5 on 2020-04-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma', '0005_auto_20200428_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='maths_upload_module_3',
            name='Title',
            field=models.CharField(default='enter subject', max_length=100),
        ),
        migrations.AddField(
            model_name='maths_upload_module_4',
            name='Title',
            field=models.CharField(default='enter subject', max_length=100),
        ),
        migrations.AddField(
            model_name='maths_upload_module_5',
            name='Title',
            field=models.CharField(default='enter subject', max_length=100),
        ),
        migrations.AddField(
            model_name='maths_upload_module_6',
            name='Title',
            field=models.CharField(default='enter subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_3',
            name='File',
            field=models.FileField(upload_to='maths/module2'),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_4',
            name='File',
            field=models.FileField(upload_to='maths/module2'),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_5',
            name='File',
            field=models.FileField(upload_to='maths/module2'),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_6',
            name='File',
            field=models.FileField(upload_to='maths/module2'),
        ),
    ]
