# Generated by Django 3.0.5 on 2020-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma', '0006_auto_20200428_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maths_upload_module_3',
            name='File',
            field=models.FileField(upload_to='maths/module3'),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_4',
            name='File',
            field=models.FileField(upload_to='maths/module4'),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_5',
            name='File',
            field=models.FileField(upload_to='maths/module5'),
        ),
        migrations.AlterField(
            model_name='maths_upload_module_6',
            name='File',
            field=models.FileField(upload_to='maths/module6'),
        ),
    ]
