# Generated by Django 3.0.5 on 2020-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0002_pdd_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdd_upload',
            name='emain',
        ),
        migrations.AddField(
            model_name='pdd_upload',
            name='email',
            field=models.CharField(default='that good', max_length=50),
        ),
        migrations.AlterField(
            model_name='pdd_upload',
            name='module',
            field=models.CharField(max_length=50),
        ),
    ]
