# Generated by Django 3.0.5 on 2020-04-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdd', '0003_auto_20200422_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdd_upload',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='pdd_upload',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='pdd_upload',
            old_name='file',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='pdd_upload',
            old_name='module',
            new_name='Module',
        ),
    ]
