# Generated by Django 3.0.5 on 2020-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_auto_20200429_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa_upload_module_3',
            name='File',
            field=models.FileField(upload_to='coa/module3'),
        ),
        migrations.AlterField(
            model_name='coa_upload_module_4',
            name='File',
            field=models.FileField(upload_to='coa/module4'),
        ),
        migrations.AlterField(
            model_name='coa_upload_module_5',
            name='File',
            field=models.FileField(upload_to='coa/module5'),
        ),
        migrations.AlterField(
            model_name='coa_upload_module_6',
            name='File',
            field=models.FileField(upload_to='coa/module6'),
        ),
    ]
